name: Testing 

on:
  push:
    branches: [ "patch/dev/brando-updatingLibsAndTesting" ]
    pull_request:
      branches: [ "dev" ]

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: submodules
      run: |
        git submodule update --init --recursive
    - name: test
      run: |
        make dependencies
        make build CONFIG=test run

