name: Testing 

on:
  push:
    branches: [ "patch/dev/brando-updatingLibsAndTesting" ]
    pull_request:
      branches: [ "dev" ]

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.PAT_TOKEN }}
    - name: building dependencies
      run: make dependencies
    - name: running tests
      run: make build CONFIG=test run
